language: node_js
sudo: required

node_js:
  - "8"

cache:
  apt: true
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - source

before_install:
- git config --global user.name "skyang"
- git config --global user.email "hhyuestc@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli

install:
- yarn

script:
- hexo clean
- hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: ./public
  github-token: $GITHUB_REPO_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master
  on:
    branch: source
