language: node_js
sudo: required

node_js:
  - "8"

cache:
  apt: true
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - source

before_install:
- git config --global user.name "skyang"
- git config --global user.email "hhyuestc@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli

install:
- yarn

script:
- hexo clean
- hexo generate

after_success:
- sed -i "s/repo_token/${GITHUB_REPO_TOKEN}/g" ./_config.yml
- Date = "$(date "+%b %d %H:%M:%S %Y")"
- sed -i "s/commit_message/[Travis] updated: $Date/g" ./_config.yml
- hexo deploy